server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/db_2021_07_28_dont_touch'
    username: postgres
    password: Admin@1234
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: 192.168.23.38
    port: 6379
  http:
    log-request-details: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.yandex.com
    port: 465
    username: test1@ecoit.com.vn
    password: tojjlztapudelvwv
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            enable: true
        transport:
          protocol: smtp
        debug: true
        timezone: Asia/Tokyo
sync: null
logging:
  level:
    springfox:
      documentation: ERROR
    org:
      springframework:
        web: DEBUG
    root: INFO
front-end:
  cas-login: 'http://192.168.10.103/#/authen?token='
cas:
  domain: 'https://192.168.10.102:8443/'
  validate: 'https://192.168.10.102:8443/cas/validate?'
  service-validate: 'https://192.168.10.102:8443/cas/proxyValidate?'
  proxy-validate: 'https://192.168.10.102:8443/cas/proxyValidate?'
  login: 'https://192.168.10.102:8443/cas/login'
  logout: 'https://192.168.10.102:8443/cas/logout'
  return-login: 'http://192.168.10.103:8080/cas/login'
configs:
  doc-out:
    auto-finish-reply-doc: true
    print-issued-data: true
  bpmn:
    one-active-for-org: false
    require-lead-under: false
    send-siblings: true
  doc-in:
    set-deadline: true
    return-previous-node: true
    review-required: true
    internal-remove: true
  doc-book:
    org_config: true
  user:
    find_by_org_and_sub: true
  clerical-org: true
  load-comment-by-org-and-position: false
  load-comment-by-org-and-position-h05: false
  genarate-phieu-trinh: false
  auto-number-in-book-doc-out: true
  remind:
    remind_for_obj: false
  send-mail: false
ocr:
  domain: http://203.205.21.146:30005/gthc_pdf
alfresco:
  domain: http://118.71.99.243:8080
  userId: admin
  password: admin
  parentIdMyFolder: 97a90643-9169-4a78-a0e6-a88ef8fa224c
  parentId: 07e81410-6600-4544-93d3-bb843f5ae8dd
  blacklist: 6ac3a9f1-ad03-4be6-b65d-8bfa9f118837,1146cb2b-6c3a-4c49-a765-1dd32c7b90fe,b161d72d-df95-4bae-8acb-dd6b26735211,f6552c9d-f713-4e92-a0a7-c2a9349baa6d,1f3b17ed-69e5-47f1-9ee0-1c926ee87780,97a90643-9169-4a78-a0e6-a88ef8fa224c,4d2ed014-b4eb-4022-bd9c-a06a8e358787
ftpConfigs:
  host: 172.16.10.246
  port: 21
  timeout: 600000
  username: bcy
  password: bcy@bcy
  active: false
ecm:
  domain: http://172.16.10.70:8081
  form:
    register: /api/TiepNhan/tiepnhapyeucau
  folder:
    register: /api/TiepNhan/tiepnhaphoso
